import {
  Document,
  Packer,
  Paragraph,
  HeadingLevel,
  AlignmentType,
  TextRun,
  Footer,
  PageNumber,
  Header,
} from 'docx';
import type { AIIA } from '../storage/schemas';

const ACCENT = '5B21B6';
const INK_900 = '0F172A';
const INK_500 = '64748B';

const SECTION_LABELS: Record<keyof AIIA['sections'], string> = {
  purpose: '1. Purpose and intended use',
  stakeholders: '2. Stakeholders',
  data: '3. Data',
  misuse: '4. Foreseeable misuse and abuse',
  fairness: '5. Fairness and bias',
  transparency: '6. Transparency and explainability',
  oversight: '7. Human oversight',
  robustness: '8. Robustness and security',
  environmental: '9. Environmental and social impact',
  lifecycle: '10. Lifecycle considerations',
};

function h(text: string, level = HeadingLevel.HEADING_2) {
  return new Paragraph({
    heading: level,
    spacing: { before: 240, after: 120 },
    children: [new TextRun({ text, bold: true, color: INK_900 })],
  });
}

function p(text: string, opts: { italic?: boolean; bold?: boolean } = {}) {
  return new Paragraph({
    spacing: { after: 120 },
    children: [new TextRun({ text, italics: opts.italic, bold: opts.bold })],
  });
}

export function generateAiiaDocx(aiia: AIIA): Document {
  const today = new Date().toISOString().slice(0, 10);

  const headerObj = new Header({
    children: [
      new Paragraph({
        alignment: AlignmentType.RIGHT,
        children: [
          new TextRun({
            text: `AI Impact Assessment — ${aiia.aiSystemName}`,
            size: 16,
            color: INK_500,
          }),
        ],
      }),
    ],
  });
  const footerObj = new Footer({
    children: [
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [
          new TextRun({ text: 'Page ', size: 16, color: INK_500 }),
          new TextRun({ children: [PageNumber.CURRENT], size: 16, color: INK_500 }),
          new TextRun({ text: ' of ', size: 16, color: INK_500 }),
          new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 16, color: INK_500 }),
          new TextRun({ text: ' — Confidential — Generated by AI Governance Toolkit', size: 16, color: INK_500 }),
        ],
      }),
    ],
  });

  const cover = [
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 1600 },
      children: [
        new TextRun({ text: 'AI Impact Assessment', size: 48, bold: true, color: ACCENT }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 480 },
      children: [
        new TextRun({ text: 'per ISO/IEC 42005', size: 24, color: INK_500 }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 480 },
      children: [
        new TextRun({ text: 'AI system: ', bold: true }),
        new TextRun({ text: aiia.aiSystemName }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 240 },
      children: [
        new TextRun({ text: 'Generated: ', bold: true }),
        new TextRun({ text: today }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({ text: `Status: ${aiia.status}`, italics: true, color: INK_500 }),
      ],
    }),
  ];

  const sectionsBlock: Paragraph[] = [];
  (Object.keys(SECTION_LABELS) as Array<keyof AIIA['sections']>).forEach((key) => {
    sectionsBlock.push(h(SECTION_LABELS[key]));
    const answers = aiia.sections[key];
    const entries = Object.entries(answers);
    if (entries.length === 0) {
      sectionsBlock.push(p('— No responses captured for this section.', { italic: true }));
    }
    for (const [q, a] of entries) {
      sectionsBlock.push(p(q, { bold: true }));
      sectionsBlock.push(p(a && a.trim() ? a : '(no response)', { italic: !a }));
    }
  });

  const signOff = [
    h('Sign-off'),
    p('Author signature: ____________________________     Date: ___________'),
    p('AI Governance lead: ____________________________   Date: ___________'),
    p('Business owner: ____________________________      Date: ___________'),
  ];

  return new Document({
    creator: 'AI Governance Toolkit',
    title: `AI Impact Assessment — ${aiia.aiSystemName}`,
    description: 'AI Impact Assessment per ISO/IEC 42005, generated by AI Governance Toolkit.',
    sections: [
      {
        headers: { default: headerObj },
        footers: { default: footerObj },
        children: [...cover, ...sectionsBlock, ...signOff],
      },
    ],
  });
}

export async function downloadAiiaWord(aiia: AIIA) {
  const doc = generateAiiaDocx(aiia);
  const blob = await Packer.toBlob(doc);
  if (typeof document === 'undefined') return;
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `AIIA-${aiia.aiSystemName.replace(/\s+/g, '-')}-${new Date().toISOString().slice(0, 10)}.docx`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
